### ISSUE TITLE
Failed to build node project on windows.

### ISSUE THREAD

**Issue by jbgoldman1104** [AuditDeploy/Builder#54]
I've downloaded builder tools from your website and tried to build node project.
But it failed.

```
C:\Users\Administrator\Documents\builder-windows>builder.exe init https://github.com/johnpapa/node-hello
panic: assignment to entry in nil map

goroutine 1 [running]:
Builder/utils.StoreBuildMetadataLocally()
        Builder/utils/metadata.go:273 +0xfd
Builder/cmd.Init()
        Builder/cmd/init.go:42 +0x131
main.main()
        Builder/main.go:21 +0x5e

```

**Comment by armondhonore** [comment]
@jbgoldman1104  can you look at the PR @jakestreet has on the windows fix PR and see if this address this problem.  

Also @jakestreet lets make sure we catch this error and add a messages related to languages not being installed / missing

**Comment by armondhonore** [comment]
@jbgoldman1104  can you pull the changes from PR #55  and see if this is resolved
